<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test test</name>
   <tag></tag>
   <elementGuidId>2f0baa38-1415-4bbc-8d84-2b7babea8ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/div[1]/svg[1]/defs[1]/pattern[1]/path[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c7ed3d9e-238d-4f84-8087-4720e1d3f2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1678096704133</value>
      <webElementGuid>985fc8ab-cad4-46ad-b73e-ebb5771146cd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
